Arguments: 
  /home/os/.nvm/versions/node/v17.9.0/bin/node /usr/share/yarn/bin/yarn.js add PinataPy

PATH: 
  /home/os/minter/bin:/home/os/.pyenv/shims:/home/os/.cairo/target/release:/home/os/.pyenv/bin:/home/os/.nvm/versions/node/v17.9.0/bin:/home/os/.cargo/bin:/home/os/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/os/Downloads/flutter/bin:/home/os/.foundry/bin:/home/os/.protostar/dist/protostar:/home/os/.protostar/dist/protostar:/home/os/Downloads/flutter/bin:/home/os/.foundry/bin:/home/os/.protostar/dist/protostar:/home/os/.protostar/dist/protostar

Yarn version: 
  1.21.1

Node version: 
  17.9.0

Platform: 
  linux x64

Trace: 
  Error: https://registry.yarnpkg.com/PinataPy: Not found
      at Request.params.callback [as _callback] (/usr/share/yarn/lib/cli.js:66947:18)
      at Request.self.callback (/usr/share/yarn/lib/cli.js:140665:22)
      at Request.emit (node:events:527:28)
      at Request.<anonymous> (/usr/share/yarn/lib/cli.js:141637:10)
      at Request.emit (node:events:527:28)
      at IncomingMessage.<anonymous> (/usr/share/yarn/lib/cli.js:141559:12)
      at Object.onceWrapper (node:events:641:28)
      at IncomingMessage.emit (node:events:539:35)
      at endReadableNT (node:internal/streams/readable:1345:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)

npm manifest: 
  No manifest

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile
